class Lang {
  Map<int, String> langEng = {
    0: 'Powered by  ',
    1: 'prison.gov.bd',
    2: 'Bangladesh Prison',
    3: 'One',
    4: 'Step',
    5: 'More',
    6: 'All Right Resurve By ',
    7: 'PRISONER TRNSFER',
    8: 'Submit',
    9: 'Enter a OTP Code ,That has been Send To ',
    10: 'OTP-XXXX',
    11: 'Let`s ',
    12: 'Prisoner Profile',
    13: 'Prisoner Appointment',
    14: 'Requested Pass',
    15: 'Mobile',
    16: 'Download Pass',
    17: 'Your Mobile Number',
    18: 'Pending',
    19: 'Request For Appointment',
    20: 'Select Appointment Date',
    21: 'Select Appointment Time',
    22: 'Number of Visitor',
    23: 'Back !',
    24: 'Verification',
    25: 'OTP SMS has sent to Your number this number',
    26: 'OTP CODE',
    27: 'Home',
    28: 'History',
    29: 'Find Doctor',
    30: 'Appointment',
    31: 'Help Desk',
    32: 'Q/A',
    33: 'Top Doctor :',
    34: 'Notification',
    35: 'Time :',
    36: 'Date :',
    37: 'Appointment',
    38: 'Name',
    39: 'Pid',
    40: 'Prisoner Id',
    41: 'CaseNo',
    42: 'DOB',
    43: 'Father Name',
    44: 'Mother Name',
    45: 'Husband Name',
    46: 'Wife Name',
    47: 'Country',
    48: 'Divison',
    49: 'District',
    50: 'SubDistrict',
    51: 'Address',
    52: 'Building Id',
    53: 'Requested Date',
    54: 'Requested Time',
    55: 'Room Id',
    56: 'Do you want to Logout',
    57: 'No',
    58: 'Yes',
    59: 'N/A',
    60: 'Wrong Number ! Check Again ',
    61: 'Ok',
    62: 'Wrong OTP ! Please Check Again ',
    63: 'Loading ...',
    64: 'Logout',
    65: 'Approved Date',
    66: 'Approved Time',
    67: 'Phone Number Field is Empty! ',
    68: 'OTP Number Field  is Empty! ',
    69: 'Do you want to take a Appointment !',
    70: 'Request Successful !',
    71: 'Account Holder',
    72: 'Field is Empty',
    73: 'Somthing wrong Try Again',
    74: 'Downloading',
    75: 'You are disconnected from the internet.',
    76: 'No Internet',
    77: 'Try Again',
    78: 'Close App',
    79: 'Type ',
    80: 'From',
    81: 'To',
    82: 'Transfer Date',
    83: 'Trasfer Time',
    84: 'Transfer Status',
    85: 'Show History',
    86: 'Close App',
    87: 'Not Found',
    88: 'Do you want to logout',
    89: 'Loction in prison',
    90: 'Current Prison',
    91: 'Prison id',
    92: 'Case No',
    93: 'Prison',
    94: 'Appointment Date :',
    95: 'Appointment Time :',
    96: 'Number of Visitor :',
    97: 'Not data Found ',
  };
  String? get(int id) {
    return langEng[id];
  }
}
